apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mischasgressernetworks.name" . }}-www
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "mischasgressernetworks.name" . }}-www
  template:
    metadata:
      labels:
        app: {{ include "mischasgressernetworks.name" . }}-www
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "mischasgressernetworks.name" . }}-www
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 7331
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          privileged: false
          capabilities:
            drop:
              - ALL
            add: ["NET_ADMIN", "SYS_TIME"]