apiVersion: apps/v1
kind: Deployment
metadata:
  name: mischasgressernetworks-www
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mischasgressernetworks-www
  template:
    metadata:
      labels:
        app: mischasgressernetworks-www
    spec:
      containers:
      - image: mgresser1981/mischasgressernetworks:latest
        name: mischasgressernetworks-www
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 7331
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          privileged: false
          capabilities:
            drop:
              - ALL
            add: ["NET_ADMIN", "SYS_TIME"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
