apiVersion: apps/v1
kind: Deployment
metadata:
  name: mischasgressernetworks-www
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mischasgressernetworks-www
  template:
    metadata:
      labels:
        app: mischasgressernetworks-www
    spec:
      containers:
      - image: mgresser/mischasgressernetworks:latest
        name: mischasgressernetworks-www
        ports:
        - containerPort: 8080
